"""
Vulnerability Engine
Orchestrates ZAP, CodeQL, and directory brute-force security scans
"""

import subprocess
import json
import logging
import os
import shutil
import tempfile
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Tuple

import requests


logger = logging.getLogger(__name__)

JS_SECURITY_SUITE = "codeql/javascript-queries:codeql-suites/javascript-security-extended.qls"
DEFAULT_OFFICIAL_FFUF_WORDLIST = Path("tools/ffuf/wordlists/common.txt")


class VulnerabilityEngine:
    """Runs ZAP, CodeQL, and directory brute-force scans against a target"""
    
    def __init__(
        self,
        target_url: str,
        output_dir: str = "scan-results",
        timeout: float = 10.0,
        verify_tls: bool = True,
    ):
        self.target_url = target_url
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)
        self.timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        # settings used by scans
        self.timeout = timeout
        self.verify_tls = verify_tls

    def check_reachability(self) -> Dict:
        """Perform a simple HTTP GET to verify the target is reachable.
        Returns a dict with an "ok" key and either status information or an error.
        """
        try:
            r = requests.get(
                self.target_url,
                timeout=self.timeout,
                verify=self.verify_tls,
                allow_redirects=True,
            )
            return {"ok": True, "status_code": r.status_code, "final_url": r.url}
        except Exception as e:
            return {"ok": False, "error": str(e)}
    
    def run_zap_scan(self) -> Dict:
        """Execute OWASP ZAP scan and return JSON results"""
        print(f"[*] Starting OWASP ZAP scan on {self.target_url}...")
        logger.info("Starting ZAP scan for %s", self.target_url)

        temp_report_path = None
        
        try:
            # Find ZAP executable from tools directory (check relative to CWD)
            zap_paths = [
                Path.cwd() / "tools" / "zap" / "ZAP_2.15.0" / "zap.bat",
                Path.cwd() / "tools" / "zap" / "zap.bat",
                Path("tools/zap/ZAP_2.15.0/zap.bat").resolve(),
                Path("tools/zap/zap.bat").resolve(),
                Path(r"C:\Program Files\OWASP\Zed Attack Proxy\zap.bat"),
                Path(r"C:\Program Files (x86)\OWASP\Zed Attack Proxy\zap.bat"),
            ]
            
            zap_cmd = None
            zap_dir = None
            for zap_path in zap_paths:
                if zap_path.exists():
                    zap_cmd = str(zap_path)
                    zap_dir = zap_path.parent
                    print(f"[*] Found ZAP at: {zap_cmd}")
                    logger.debug("ZAP executable resolved to %s", zap_cmd)
                    break
            
            if not zap_cmd:
                print("[!] ZAP not found. Checked:")
                for p in zap_paths:
                    print(f"    {p}")
                    logger.debug("ZAP path checked: %s", p)
                return {}

            with tempfile.NamedTemporaryFile(delete=False, suffix=".json") as temp_report:
                temp_report_path = Path(temp_report.name)
            
            #ZAP command line (quickout means quick scan ruleset, less through, much faster)
            cmd = [zap_cmd, "-cmd", "-quickurl", self.target_url, "-quickout", str(temp_report_path)]


            
            # Run ZAP from its own directory so it can find JAR
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=300, cwd=str(zap_dir))
            
            if result.returncode != 0:
                print(f"[!] ZAP warning: {result.stderr}")
                logger.warning("ZAP returned non-zero exit code %s: %s", result.returncode, result.stderr)
            
            # temp report path generated by zap
            if temp_report_path and temp_report_path.exists():
                with open(temp_report_path, encoding="utf-8") as f:
                    return json.load(f)
            else:
                print("[!] ZAP report not generated")
                logger.warning("ZAP report was not generated")
                return {}
                
        except subprocess.TimeoutExpired:
            print("[!] ZAP scan timed out (5 minutes)")
            logger.error("ZAP scan timed out")
            return {}
        except Exception as e:
            print(f"[!] ZAP scan failed: {e}")
            logger.exception("ZAP scan failed")
            return {}
        finally:
            if temp_report_path and temp_report_path.exists():
                try:
                    temp_report_path.unlink()
                except OSError:
                    logger.debug("Failed to remove temporary ZAP report: %s", temp_report_path)
    
    def run_codeql_scan(self, source_path: str = None) -> Dict:
        """Execute CodeQL scan and return SARIF results"""
        print(f"[*] Starting CodeQL scan...")
        logger.info("Starting CodeQL scan")

        if source_path is None:
            print("[!] CodeQL requires source code path. Provide --source-path <path>.")
            logger.warning("CodeQL source path missing; skipping CodeQL scan")
            return {"runs": []}
        
        # validate source path and resolve to absolute path
        source_root = Path(source_path).expanduser().resolve()

        # if the path doesn't exist or isn't a directory, return empty results
        if not source_root.exists() or not source_root.is_dir():
            print(f"[!] Invalid --source-path: {source_root}")
            logger.warning("Invalid CodeQL source path: %s", source_root)
            return {"runs": []}

        source_path = str(source_root)
        print(f"[*] Scanning source at: {source_path}")
        logger.debug("CodeQL source path: %s", source_path)
        
        temp_dir = None
        try:
            # locate codeql executable in tools folder
            codeql_candidates = [
                Path.cwd() / "tools" / "codeql" / "codeql" / "codeql.exe",
                Path.cwd() / "tools" / "codeql" / "codeql.exe",
                Path("tools/codeql/codeql/codeql.exe").resolve(),
                Path("tools/codeql/codeql.exe").resolve(),
            ]

            codeql_cmd = None
            for candidate in codeql_candidates:
                if candidate.exists():
                    codeql_cmd = str(candidate)
                    break

            if not codeql_cmd:
                codeql_cmd = "codeql"

            # create temp directory for codeql database and results
            temp_dir = Path(tempfile.mkdtemp(prefix="codeql_scan_"))
            db_dir = temp_dir / "db"
            sarif_output = temp_dir / "results.sarif"

            env = os.environ.copy()
            env['PYTHONIOENCODING'] = 'utf-8'
            env['PYTHONUTF8'] = '1'

            # create db
            create_cmd = [
                codeql_cmd,
                "database",
                "create",
                str(db_dir),
                "--language=javascript-typescript",
                "--source-root",
                source_path,
                "--build-mode=none",
                "--overwrite",
            ]

            print("[*] Building CodeQL database...")
            create_result = subprocess.run(create_cmd, capture_output=True, text=True, timeout=900, env=env)
            
            if create_result.returncode != 0:
                logger.warning("CodeQL database creation failed: %s", create_result.stderr[-500:])
                print("[*] Retrying CodeQL database creation without autobuild...")

                fallback_create_cmd = create_cmd + ["--build-mode=none"]
                create_result = subprocess.run(fallback_create_cmd, capture_output=True, text=True, timeout=900, env=env)
                if create_result.returncode != 0:
                    logger.error("CodeQL database creation failed without autobuild: %s", create_result.stderr[-500:])
                    print("[!] CodeQL database creation failed")
                    return {"runs": []}
            # codeql scan commandline
            analyze_cmd = [
                codeql_cmd,
                "database",
                "analyze",
                str(db_dir),
                JS_SECURITY_SUITE,
                "--download",
                "--format=sarif-latest",
                "--output",
                str(sarif_output),
            ]

            print("[*] Running CodeQL analysis...")
            analyze_result = subprocess.run(analyze_cmd, capture_output=True, text=True, timeout=900, env=env)
            if analyze_result.returncode != 0:
                logger.error("CodeQL analysis failed: %s", analyze_result.stderr[-500:])
                print("[!] CodeQL analysis failed")
                return {"runs": []}

            if sarif_output.exists():
                with open(sarif_output, "r", encoding="utf-8") as file:
                    sarif_data = json.load(file)
                findings_count = sum(len(run.get("results", [])) for run in sarif_data.get("runs", []))
                if findings_count > 0:
                    print(f"[*] CodeQL found {findings_count} potential issues")
                    logger.info("CodeQL found %s issues", findings_count)
                else:
                    print("[*] CodeQL scan complete - no issues found")
                    logger.info("CodeQL completed with zero findings")
                return sarif_data

            print("[*] CodeQL scan complete - no SARIF output generated")
            logger.info("CodeQL completed with no SARIF output")
            return {"runs": []}
        except FileNotFoundError:
            print("[!] CodeQL CLI not found. Run scripts/before_setup.bat to install CodeQL.")
            logger.error("CodeQL executable not found")
            return {"runs": []}
        except subprocess.TimeoutExpired:
            print("[!] CodeQL scan timed out")
            logger.error("CodeQL scan timed out")
            return {"runs": []}
        except Exception as e:
            print(f"[!] CodeQL scan failed: {e}")
            logger.exception("CodeQL scan failed")
            return {"runs": []}
        finally:
            if temp_dir and temp_dir.exists():
                try:
                    shutil.rmtree(temp_dir, ignore_errors=True)
                except Exception:
                    logger.debug("Failed to cleanup CodeQL temp dir: %s", temp_dir)

    def run_dirscan_scan(
        self,
        wordlist_path: str = None,
        recursive: bool = True,
        recursion_depth: int = 2,
        threads: int = 80,
        
    ) -> Dict:
        """Execute a directory brute-force scan and return discovered paths."""
        print(f"[*] Starting directory scan on {self.target_url}...")
        logger.info("Starting directory scan for %s", self.target_url)

        temp_dir = None
        wordlist_file = None

        try:
            ffuf_candidates = [
                Path.cwd() / "tools" / "ffuf" / "ffuf.exe",
                Path.cwd() / "tools" / "ffuf" / "ffuf",
                Path("tools/ffuf/ffuf.exe").resolve(),
                Path("tools/ffuf/ffuf").resolve(),
            ]

            ffuf_cmd = None
            for candidate in ffuf_candidates:
                if candidate.exists():
                    ffuf_cmd = str(candidate)
                    break

            if not ffuf_cmd:
                ffuf_cmd = shutil.which("ffuf") or shutil.which("ffuf.exe")

            if not ffuf_cmd:
                print("[!] Directory scanner not found. Run scripts/before_setup.bat to install ffuf.")
                logger.warning("directory scanner executable not found")
                return {"results": []}
            # determine wordlist to use, prioritize user-provided, then official, and validate existence
            if wordlist_path:
                candidate = Path(wordlist_path).expanduser().resolve()
                if not candidate.exists() or not candidate.is_file():
                    print(f"[!] Invalid dirscan wordlist: {candidate}")
                    logger.warning("Invalid dirscan wordlist: %s", candidate)
                    return {"results": []}
                wordlist_file = candidate
            else:
                official_candidates = [
                    (Path.cwd() / "tools" / "ffuf" / "wordlists" / "common.txt").resolve(),
                    DEFAULT_OFFICIAL_FFUF_WORDLIST.resolve(),
                ]
                for official in official_candidates:
                    if official.exists() and official.is_file():
                        wordlist_file = official
                        break

                if not wordlist_file:
                    print("[!] Official ffuf wordlist not found. Run scripts/before_setup.bat or provide --dirscan-wordlist.")
                    logger.warning("Official ffuf wordlist not found and no custom wordlist was provided")
                    return {"results": []}
            # temporary file for ffuf JSON output
            with tempfile.NamedTemporaryFile(delete=False, suffix=".json") as temp_output:
                output_path = Path(temp_output.name)

            target_base = self.target_url.rstrip("/")
            cmd = [
                ffuf_cmd,
                "-u",
                f"{target_base}/FUZZ",
                "-w",
                str(wordlist_file),
                "-of",
                "json",
                "-o",
                str(output_path),
                "-ac",
                "-mc",
                "200,204,301,302,307,308,401,403,405",
                "-t",
                str(max(1, threads)),
            ]

            if recursive:
                cmd.extend(["-recursion", "-recursion-depth", str(max(0, recursion_depth)), "-recursion-strategy", "greedy"])

            

            print("[*] Running directory brute-force scan...")
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=900)
            if result.returncode not in (0, 1):
                print(f"[!] dirscan warning: {result.stderr}")
                logger.warning("directory scanner returned non-zero exit code %s: %s", result.returncode, result.stderr)

            if output_path.exists():
                with open(output_path, "r", encoding="utf-8") as handle:
                    return json.load(handle)

            print("[*] Directory scan complete - no JSON output generated")
            logger.info("Directory scan completed with no output")
            return {"results": []}
        except subprocess.TimeoutExpired:
            print("[!] Directory scan timed out")
            logger.error("Directory scan timed out")
            return {"results": []}
        except Exception as e:
            print(f"[!] Directory scan failed: {e}")
            logger.exception("Directory scan failed")
            return {"results": []}
        finally:
            if temp_dir and temp_dir.exists():
                try:
                    shutil.rmtree(temp_dir, ignore_errors=True)
                except Exception:
                    logger.debug("Failed to cleanup directory scan temp dir: %s", temp_dir)
            if 'output_path' in locals() and output_path.exists():
                try:
                    output_path.unlink()
                except OSError:
                    logger.debug("Failed to remove temporary directory scan output: %s", output_path)
    
    def run(
        self,
        run_zap: bool = True,
        run_codeql: bool = True,
        run_dirscan: bool = False,
        source_path: str = None,
        dirscan_wordlist: str = None,
        dirscan_recursive: bool = True,
        dirscan_depth: int = 2,
        dirscan_threads: int = 80,
        
    ) -> Dict:
        """Run configured scans and return raw results"""
        print(f"\n{'=' * 80}")
        print(f"Starting security scan of {self.target_url}")
        print(f"{'=' * 80}\n")
        
        results = {}
        effective_dirscan_threads = dirscan_threads
        if run_zap and run_codeql and run_dirscan:
            effective_dirscan_threads = min(dirscan_threads, 25) #means that max is 25 threads for dirscan if all 3 scans are enabled, otherwise it can use the full amount specified by user
        
        # ensure the target is reachable before running scans that rely on reachability, but still allow CodeQL to run if the target is down since it only needs source code
        reachable = True
        if run_zap or run_dirscan:
            reach = self.check_reachability()
            if not reach.get("ok"):
                reachable = False
                print(f"[!] Target not reachable: {reach.get('error')}")

        tasks = {}
        with ThreadPoolExecutor(max_workers=max(1, sum([run_zap, run_codeql, run_dirscan]))) as executor:
            if run_zap and reachable:
                tasks[executor.submit(self.run_zap_scan)] = "zap"

            if run_codeql:
                tasks[executor.submit(self.run_codeql_scan, source_path)] = "codeql"

            if run_dirscan and reachable:
                tasks[executor.submit(
                    self.run_dirscan_scan,
                    wordlist_path=dirscan_wordlist,
                    recursive=dirscan_recursive,
                    recursion_depth=dirscan_depth,
                    threads=effective_dirscan_threads,
                    
                )] = "dirscan"

            if run_zap and not reachable:
                results["zap"] = {}

            if run_dirscan and not reachable:
                results["dirscan"] = {"results": []}

            for future in as_completed(tasks):
                results[tasks[future]] = future.result()
        
        return results
